# Generated by Django 4.2.18 on 2025-03-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_maderecipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MadeRecipe',
        ),
    ]
