# Generated by Django 4.2.18 on 2025-03-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_maderecipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
