# Generated by Django 4.2.18 on 2025-02-06 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipeingredient_trackedingredient_scrapedrecipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedrecipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.scrapedrecipe'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scrapedrecipe',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapedrecipe',
            name='ready_in_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scrapedrecipe',
            name='servings',
            field=models.IntegerField(default=1),
        ),
    ]
