# Generated by Django 4.2.18 on 2025-02-13 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_scrapedrecipe_ingredients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cook_time', models.CharField(default='Unknown', max_length=50)),
                ('prep_time', models.CharField(default='Unknown', max_length=50)),
                ('category', models.CharField(default='Uncategorized', max_length=100)),
                ('servings', models.IntegerField(default=4)),
                ('calories', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('instructions', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='author',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutrition_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.CharField(choices=[('dataset', 'Dataset'), ('bbc', 'BBC Food')], default='dataset', max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='DatasetIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_ingredients', to='recipes.datasetrecipe')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='recipes_dat_name_a240f3_idx')],
            },
        ),
    ]
