# Generated by Django 4.2.18 on 2025-02-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_datasetrecipe_calories_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='datasetrecipe',
            name='recipes_dat_created_f3f4b0_idx',
        ),
        migrations.RemoveField(
            model_name='datasetrecipe',
            name='created_at',
        ),
        migrations.AddField(
            model_name='datasetrecipe',
            name='ingredients_list',
            field=models.TextField(default='[]'),
        ),
    ]
