# Generated by Django 4.2.18 on 2025-02-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_author_recipe_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetrecipe',
            name='ingredients_parts',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='datasetrecipe',
            name='ingredients_quantities',
            field=models.TextField(default='[]'),
        ),
    ]
