# Generated by Django 4.2.18 on 2025-02-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_datasetrecipe_ingredients_parts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetrecipe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasetrecipe',
            name='images',
            field=models.TextField(default='[]'),
        ),
    ]
