# Generated by Django 4.2.18 on 2025-03-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_datasetrecipe_description_datasetrecipe_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='images',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients_parts',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients_quantities',
            field=models.TextField(default='[]'),
        ),
    ]
