# Generated by Django 4.2.18 on 2025-03-20 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_triedrecipe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='triedrecipe',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='triedrecipe',
            name='dataset_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.datasetrecipe'),
        ),
        migrations.AlterField(
            model_name='triedrecipe',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
        migrations.AddConstraint(
            model_name='triedrecipe',
            constraint=models.UniqueConstraint(condition=models.Q(('recipe__isnull', False)), fields=('user', 'recipe'), name='unique_user_recipe'),
        ),
        migrations.AddConstraint(
            model_name='triedrecipe',
            constraint=models.UniqueConstraint(condition=models.Q(('dataset_recipe__isnull', False)), fields=('user', 'dataset_recipe'), name='unique_user_dataset_recipe'),
        ),
    ]
