# Generated by Django 4.2.18 on 2025-03-20 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_alter_triedrecipe_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triedrecipe',
            name='points_earned',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='triedrecipe',
            name='dataset_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.datasetrecipe'),
        ),
        migrations.AlterField(
            model_name='triedrecipe',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.recipe'),
        ),
    ]
