# Generated by Django 4.2.18 on 2025-04-01 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_triedrecipe_points_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triedrecipe',
            name='scraped_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.scrapedrecipe'),
        ),
        migrations.AddConstraint(
            model_name='triedrecipe',
            constraint=models.UniqueConstraint(condition=models.Q(('scraped_recipe__isnull', False)), fields=('user', 'scraped_recipe'), name='unique_user_scraped_recipe'),
        ),
    ]
