# Generated by Django 4.2.18 on 2025-04-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_shoprecipe_purchasedrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='points_cost',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
