# Generated by Django 4.2.18 on 2025-04-18 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_recipe_created_by_user_recipe_is_premium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Private notes for admins reviewing this recipe', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Review'), ('approved', 'Approved'), ('premium', 'Premium'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='shoprecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_listing', to='recipes.recipe'),
        ),
    ]
