# Generated by Django 4.2.18 on 2025-04-18 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0027_recipe_admin_notes_recipe_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
